@extends('layouts.default')
@section('content')
    <p class="services-heading">COSMETIC BREAST SURGERY</p>
    <p><span class="sub-heading-bold">Subcutaneous mastectomy: Subcutaneous mastectomy is a surgery that removes most of the breast tissue but preserves the nipple and areola. It is usually done for prophylactic reasons (to prevent breast cancer) or for gender affirmation (in transgender men). It may be followed by breast reconstruction or chest contouring.</p>
    <p><span class="sub-heading-bold">Gynecomastia treatment: Gynecomastia treatment is a surgery that reduces the size and improves the shape of the breasts in men or people assigned male at birth who have enlarged breast tissue. It can involve liposuction, excision of excess skin and glandular tissue, or a combination of both.</p>
    <p><span class="sub-heading-bold">Breast augmentation surgery: Breast augmentation surgery is a surgery that increases the size and enhances the shape of the breasts in women or people assigned female at birth who have small or asymmetrical breasts. It can involve placing implants or transferring fat from another part of the body to the breasts.</p>
    <p><span class="sub-heading-bold">Breast reduction surgery: Breast reduction surgery is a surgery that decreases the size and improves the shape of the breasts in women or people assigned female at birth who have large or heavy breasts that cause physical or emotional discomfort. It can involve removing excess skin, fat, and glandular tissue, and repositioning the nipple and areola.</p>
    <p><span class="sub-heading-bold">Breast uplift surgery: Breast uplift surgery is a surgery that lifts and tightens the breasts in women or people assigned female at birth who have sagging or drooping breasts due to aging, pregnancy, breastfeeding, or weight loss. It can involve removing excess skin, reshaping the breast tissue, and repositioning the nipple and areola. It can be done alone or with breast augmentation or reduction.</p>
    <p><span class="sub-heading-bold">Inverted nipple surgery: Inverted nipple surgery is a surgery that corrects the appearance of nipples that are retracted or pulled inward. It can involve releasing the fibrous bands that cause the inversion, preserving or restoring the milk ducts, and securing the nipple in an outward position.</p>
    <p><span class="sub-heading-bold">Correction lipomodelling breast augmentation: Correction lipomodelling breast augmentation is a surgery that uses fat from another part of the body to increase the size and improve the shape of the breasts in women or people assigned female at birth who have small, asymmetrical, or irregular breasts. It can also correct the complications or dissatisfaction from previous breast augmentation with implants.</p>
@stop
