@extends('layouts.default')
@section('content')
<p class="services-heading-1 mt-3 mb-3">BREAST RECONSTRUCTION</p>
<p><span class="sub-heading-bold">Immediate and late breast reconstruction:</span> Breast reconstruction is the surgical creation of a new breast shape after a mastectomy or lumpectomy. It can be done at the same time as the breast cancer surgery (immediate reconstruction) or after the wound has healed and the cancer treatment has finished (late reconstruction).</p>
<p><span class="sub-heading-bold">Nipple reconstruction:</span> Nipple reconstruction is the surgical creation of a new nipple and areola on the reconstructed breast. It can be done as a separate procedure after the breast reconstruction or as part of the breast reconstruction. It can use skin from the breast or another part of the body, or a tattoo or a prosthesis</p>
<p><span class="sub-heading-bold">Local flaps including LICAP, MICAP, Grisotti flap, LTAP, TDAP, LD flap:</span> Local flaps are techniques that use skin, fat, and sometimes muscle from the chest or back area to reconstruct the breast. They are usually combined with an implant to provide enough volume. Some examples of local flaps are: LICAP (lateral intercostal artery perforator), MICAP (medial intercostal artery perforator), Grisotti flap, LTAP (lateral thoracic artery perforator), TDAP (thoracodorsal artery perforator), and LD flap (latissimus dorsi).</p>
<p><span class="sub-heading-bold">Implant based reconstruction:</span> Implant based reconstruction is a technique that uses a saline or silicone implant to create the new breast shape. It may require a tissue expander to stretch the skin and muscle before placing the implant. It may also use acellular dermal matrix or mesh to support the implant.</p>
<p><span class="sub-heading-bold">Implant and LD based reconstructions:</span> Implant and LD based reconstructions are techniques that combine an implant and a latissimus dorsi flap to reconstruct the breast. The latissimus dorsi flap provides extra skin, fat, and muscle to cover and support the implant. It is taken from the back and tunneled under the skin to the chest.</p>
<p><span class="sub-heading-bold">Lipomodeling based reconstruction:</span> Lipomodeling based reconstruction is a technique that uses fat from another part of the body, such as the abdomen or thighs, to enhance the shape and volume of the reconstructed breast. It is also called fat grafting or fat transfer. It can be used alone or in combination with other techniques.</p>
<p><span class="sub-heading-bold">Autologous based reconstruction (pedicled and free flap):</span> Autologous based reconstruction is a technique that uses a flap of tissue from another part of the body, such as the abdomen, buttocks, or thighs, to create the new breast shape. The flap contains skin, fat, blood vessels, and sometimes muscle. It can be either pedicled (attached to its original blood supply) or free (detached and reconnected to the chest blood vessels).</p>
<p><span class="sub-heading-bold">Reconstruction including DIEP flap, TUG flap, PAP flap:</span> These are examples of autologous based reconstruction using free flaps. The DIEP flap (deep inferior epigastric perforator) uses tissue from the lower abdomen. The TUG flap (transverse upper gracilis) uses tissue from the inner thigh. The PAP flap (profunda artery perforator) uses tissue from the back of the thigh.</p>

@stop
